### ISSUE TITLE
Add timestamps to each scenario run & http request

### ISSUE THREAD

**Issue by tsiq-brianvs** [twosigma/webtau#133]
This will be useful for correlating failed integration tests to the logs, which will help drill down into root cause quickly.

Timestamps could be in ISO8601 format with the system's timezone e.g. 2008-09-15T15:53:00.123-04:00

* Under tests -> Summary, please add two cards. Labels: "Scenario Start" and "Scenario End" with the values as the timestamps.
* For each HTTP call under http calls -> individual call, please add a single card (currently just has "Latency (ms)"). Label: "Request Start" with the timestamp.
* Under tests -> HTTP calls, please include Request Timestamp as a column.

**Comment by MykolaGolubyev** [comment]
Seems reasonable. What about console output log during tests run?

**Comment by tsiq-brianvs** [comment]
That'd also be great, maybe "<timestamp> Beginning scenario <scenario>" and "<timestamp> <method> <url>"

**Comment by MykolaGolubyev** [comment]
I can see how it could become noisy though. Need to think about it.

**Comment by tsiq-brianvs** [comment]
Maybe it could be opt-in, disabled by default? 
Also fine just having the timestamps in the report.

**Comment by MykolaGolubyev** [comment]
@tsiq-brianvs do we actually need end-time giving that we will have start time and latency in report?

**Comment by tsiq-brianvs** [comment]
Ah, no we don't.

**Comment by MykolaGolubyev** [comment]
![image](https://user-images.githubusercontent.com/11657860/44240458-2f8c0900-a18c-11e8-9c17-d382ec38427e.png)
![image](https://user-images.githubusercontent.com/11657860/44240471-416dac00-a18c-11e8-94f1-5be03f1a6c4b.png)
