### ISSUE TITLE
Include custom headers in report

### ISSUE THREAD

**Issue by tsiq-karold** [twosigma/webtau#139]
If my http.get call (for example) specifies a header, it would be useful to include it in the report.

**Comment by MykolaGolubyev** [comment]
it is going to be hard to distinct which one are specified  manually vs by providers.
Should we include request header period?

**Comment by tsiq-karold** [comment]
I thought it might be but hoped webtau might have some magic to help 😄 

The only issue with including all is it's likely to include an auth header which will make the report less shareable.  Can we exclude cookies and `Authorization` headers?

**Comment by tsiq-nick** [comment]
That seems reasonable.

**Comment by MykolaGolubyev** [comment]
while we are here, should we include response header as well?

**Comment by tsiq-karold** [comment]
I raised this issue because I was debugging a problem and needed to look at the request headers but generally, I suspect one might want to look at those too, particularly things like Location and Link headers.

Do we need to worry about any auth filtration though?

**Comment by MykolaGolubyev** [comment]
maybe reduct Set-Cookies header? I am not sure if SAML or other auth protocols return tokens through headers.

**Comment by tsiq-karold** [comment]
The ones I've used have been body.

**Comment by MykolaGolubyev** [comment]
addressed in #142
