### ISSUE TITLE
Add swagger validation as a test step

### ISSUE THREAD

**Issue by MykolaGolubyev** [twosigma/webtau#147]
Swagger validation action needs to appear in report as a step.

**Comment by tsiq-karold** [comment]
What's the usecase for that?  Expectations validation does not appear explicitly, only if it fails so trying to understand why swagger is being treated differently.

**Comment by MykolaGolubyev** [comment]
Idea is to use "Steps" tab in a report to understand where time is spent. We have tests that say 1s total by http calls total time is 0.5s.  Want to add transparency to test. Another candidate could be implicit HTTP headers provider.

**Comment by tsiq-karold** [comment]
OK, makes sense.  Should it include expectations processing too then?  It's not unfeasible someone would put something crazy in there.

**Comment by MykolaGolubyev** [comment]
could you elaborate on "expectations processing"?

**Comment by tsiq-karold** [comment]
When you do something like:
```
http.get('blah') {
    someLongRunningMethod()
}
```

That lambda could in theory contain any code and therefore not be fast.

**Comment by MykolaGolubyev** [comment]
webtau has a concept of `action` that is not well documented. It suppose to create a `step` with a custom description. May be a good idea to expose and document those. 
`LazyResource` could be using already.
