### ISSUE TITLE
Provide a way to skip execution of all scenarios in certain failure cases

### ISSUE THREAD

**Issue by tsiq-karold** [twosigma/webtau#194]
The primary use case for this is if you fail to obtain creds in a header provider then in all likelihood no tests will pass therefore may as well abandon the test run straight away.  Right now if an exception is thrown from the header provider webtau will still try all scenarios.

One option would be to have a special exception type, e.g. `AbortTestExecutionException`, that can be thrown and skips further scenario execution.  There may be a better way though.

**Comment by tsiq-karold** [comment]
For my usecase I need to skip *all* tests but I can imagine cases where one might want to skip only for the current file.

**Comment by tsiq-nick** [comment]
Wonder what is the behavior for parallel run should be.

**Comment by tsiq-karold** [comment]
It could just exit like in serial mode.  Only difference would be more than one test might have attempted execution.  The point of this really is to exit as early as possible.

**Comment by MykolaGolubyev** [comment]
added `terminateAll('reason')`
