### ISSUE TITLE
Comparison of sets is ordered

### ISSUE THREAD

**Issue by tsiq-rob** [twosigma/webtau#209]
It appears that comparing two java (hash)sets:

```set1.should == set2```

does not work correctly. The comparison is ordered elementwise - we ought to use set equality semantics here instead.

**Comment by tsiq-nick** [comment]
Was about to implement it today and bumped into an interesting question.
Should we just use `contains` on a `set` or should each comparison go through extended equality rules. 
e.g. comparison of set of strings and set of regexps. There is a rule to compare string and regexp. And usually that rule is propagated down like in case of two iterables.

```
actual: ['hello', 'world'] as Set
expected: [~/worl./, ~/he..o/] as Set
```

@tsiq-karold, @tsiq-rob thoughts?

**Comment by tsiq-karold** [comment]
If this is propagated down for iterables, I would think it ought to for sets also.  Unless you want to introduce a new matcher for unordered set comparison but I'm not sure I like that idea.

**Comment by tsiq-rob** [comment]
So let's see if I understand the behaviour correctly. `==` will pass if the two sets have the same size and if each item in `expected` is considered equal to a different item in `actual`?

If that's right it seems reasonable
