### ISSUE TITLE
AST replacement does not handle properties with dashes

### ISSUE THREAD

**Issue by tsiq-karold** [twosigma/webtau#211]
Example test to reproduce the problem:
```
http.get('url') {
    header.content-encoding.should == 'gzip'
}
```
This throws the following error:
```
Caused by: java.lang.IllegalStateException: this method call should have been replaced with AST
```

**Comment by MykolaGolubyev** [comment]
This is not a valid groovy syntax. Should we close it?
Groovy may treat it like 
```
header.content - encoding.should
```
I agree that error could be better. if that's the case we should leave it.

**Comment by tsiq-karold** [comment]
Yes, I wasn't suggesting we handle this, agree it's not valid.  Was mostly about improving the error message.   IIRC we made a change to create a camel case entry for this anyway so perhaps not such an issue.
