### ISSUE TITLE
Matcher enhancements: <, >, <=, >= and date compatibility

### ISSUE THREAD

**Issue by tsiq-karold** [twosigma/webtau#24]
I would like to be able to do something like:
```
body.someDate.should <= LocalDate.now()
```
Or something similar.

**Comment by MykolaGolubyev** [comment]
added `beGreatearThan`, `beLessThan`, `beGreaterThanOrEqual`, `beLessThanOrEqual` for now.
Handling of `<=` requires AST and AST is not implemented yet, even for ==.
