### ISSUE TITLE
Webtau should follow redirects rather than relying on HttpURLConnection

### ISSUE THREAD

**Issue by tsiq-karold** [twosigma/webtau#269]
This will allow us to record information about the redirect as steps and hence for it to appear in the report.  Need to be careful with a few things like circular redirects, etc though.

**Comment by tsiq-clemens** [comment]
this just hit home when we ran afoul of the java version change from 181 to 191:

> "➜ Better HTTP Redirection Support 
> In this release, the behavior of methods which application code uses to set request properties in java.net.HttpURLConnection has changed. When a redirect occurs automatically from the original destination server to a resource on a different server, then all such properties are cleared for the redirect and any subsequent redirects. If these properties are required to be set on the redirected requests, then the redirect responses should be handled by the application by calling HttpURLConnection.setInstanceFollowRedirects(false) for the original request.
> 
> JDK-8196902 (not public)"

**Comment by tsiq-clemens** [comment]
java example (old but probably relevant): https://www.mkyong.com/java/java-httpurlconnection-follow-redirect-example/
