### ISSUE TITLE
Path based access to DataNode fields

### ISSUE THREAD

**Issue by tsiq-karold** [twosigma/webtau#282]

**Comment by MykolaGolubyev** [comment]
will it include ad-hoc filters and projections? or will it be narrow down dot separated with optional index access only?

**Comment by tsiq-karold** [comment]
My initial feeling was for the purposes of the `get` on `DataNode`, we could support full JSONPath syntax.  For the purposes of using this for https://github.com/twosigma/webtau/issues/221 we only allow dot and index access but I haven't fully thought this through yet.  Wanted to get the issue raised so we don't forget.

**Comment by tsiq-karold** [comment]
Sorry, I meant for #221 we allow dot, index and filtration but no projection.

**Comment by tsiq-karold** [comment]
Discussed this with @MykolaGolubyev, we propose to allow dot and index based access only.  For example:
```groovy
http.get('/foo/123') {
    body.get("a.b.c").should == "blah"
    body.get("a.b.d").should == ["first", "second", "last"]
    body.get("a.b.d[0]").should == "first"
    body.get("a.b.d[-1]").should == "last"
}
```
