### ISSUE TITLE
Exceptions outside of scenario should be caught, not cause webtau to fail

### ISSUE THREAD

**Issue by tsiq-brian** [twosigma/webtau#289]
# Steps

```
package scenarios

import static com.twosigma.webtau.WebTauGroovyDsl.scenario

throw new RuntimeException("kaboom")

scenario("failure") {
    true.should == false
}
```

When this scenario is run, no output report is given, remaining tests aren't run (if any).

Expected behavior: maybe entire file should be marked as a failure, no tests run. or something else to that effect and is reasonable.

**Comment by tsiq-karold** [comment]
I think it would make sense to capture these sorts of exceptions into a "setup failures" type of category or at a minimum, catch them and produce a useful error to console rather than printing a 200 line stack trace with no useful message 😁

**Comment by MykolaGolubyev** [comment]
Agree. It is a good catch.
