### ISSUE TITLE
Extensible rules for `add`, `subtract`, `plus`, `minus`

### ISSUE THREAD

**Issue by MykolaGolubyev** [twosigma/webtau#299]
With introduction of `TableData`'s `cell.above.plus(x)` we need a way to extend the math for various types in a way that it works with Java. E.g. `_____.plus(1)` or `___ + 1` (for Groovy) where `____` defined as `LocalDate.of(...)`.

We also need to expose this math outside of TableData cells. So something like `add(localDate, 1)` should be available. 

Rules need to be discoverable in a similar manner how `CompareToHandler`s are. A handful of rules should be available out of the box.

**Comment by MykolaGolubyev** [comment]
@tsiq-karold , @tsiq-clemens thoughts?

**Comment by tsiq-karold** [comment]
No real thoughts other than it seems sensible though feels like a lot of effort for small benefit, especially in Java (in Groovy I can see the benefit if it allows you to infix operators).  Things like numbers, dates, etc. already have appropriate functions.

**Comment by MykolaGolubyev** [comment]
To be honest, my main use case is to auto increment `date` in a column
```
def increment = cell.above + 1
....
cell.rowIdx | LocalDate.of(...)   | ....
cell.rowIdx | increment .         | ...
cell.rowIdx | increment           | ...
```
Unfortunately even for groovy it won't work out of the box.
