### ISSUE TITLE
Http.post has no overrides that allow specifying query params

### ISSUE THREAD

**Issue by tsiq-karold** [twosigma/webtau#327]

**Comment by MykolaGolubyev** [comment]
go for it!

**Comment by tsiq-karold** [comment]
How would you feel about creating fluent APIs for http also (in addition to existing ones, not instead of)?  The number of overrides is starting to get unmaintainable and I suspect there are other permutations which are not catered for right now.

**Comment by MykolaGolubyev** [comment]
My preference would be to avoid it. I think there is a limited set of permutations. Feels like that query param one is the last missing one for post/put/delete. 
Fluent API may be a bit problematic to match well with validation Closures (last parameter syntax sugar in Groovy).  Or the flow may become a bit unnatural (e.g. rest-assured api style).
Do you have an example in mind?

**Comment by tsiq-karold** [comment]
All fair points, I'm not super keen on fluent API for this sort of usecase either but the number of overrides is crazy.  The other problem is for `get` we have overries which take `HttpParams` and some which take just a map for the params.  We can't do that to the same extent for `post` because there are overrides which take a map for the body.  Fluent would solve that.

Perhaps we leave as is and if we have to add yet another optional param, and hence N overrides, we'll reconsider.

**Comment by MykolaGolubyev** [comment]
Also fair. Definitely taking a hit here on behalf of users. 
Maybe we should deprecate `http.get` with map for query params. And remove them in `2.0`. Don't need to replicate that to post/put/delete

**Comment by tsiq-karold** [comment]
Makes sense.  Sounds like a plan!
