### ISSUE TITLE
Cli scripts location resolution

### ISSUE THREAD

**Issue by MykolaGolubyev** [twosigma/webtau#359]
When you run your script (as opposite to a system command like `curl`), there should be a script location resolution.

Open questions:
* how to decide whether to `resolve` a given command/scrip or not. one possible solution is to try to resolve and if it works, use resolved version.
* how to specify resolution locations. Ideally it should be an array of locations, but we need to be able to override the value through command line. Should it be a `;` delimited string?

**Comment by tsiq-karold** [comment]
Can we not delegate this to the OS and allow one to specify a PATH in cfg?  If we allow PATH, it should probably either use the system delimiter or we allow the PATH to be a list in the cfg.

**Comment by MykolaGolubyev** [comment]
@tsiq-karold that should work. Thanks for reminding about `PATH`.
