### ISSUE TITLE
Should not have a non-test dependency on slf4j-simple

### ISSUE THREAD

**Issue by tsiq-karold** [twosigma/webtau#373]
This causes problems if using webtau via JUnit because the app under test will almost certainly want to be in control of the actual slf4j binding to be used.

I think this should move from `runtime` to `testRuntime`.

**Comment by MykolaGolubyev** [comment]
need to figure out what is requiring it, maybe a browser selenium code, bur right now we regressed into having a message 
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
