### ISSUE TITLE
Statistics in the html report should be properly formatted

### ISSUE THREAD

**Issue by tsiq-karold** [twosigma/webtau#383]
We should probably limit averages to a couple decimal places.

<img width="564" alt="Screenshot 2019-07-18 at 08 27 59" src="https://user-images.githubusercontent.com/33879397/61437906-12c8fa00-a936-11e9-8b2d-f0d6f5398037.png">

**Comment by MykolaGolubyev** [comment]
That's weird as we have 
```
            <CardWithElapsedTime label="Average Time"
                                 millis={report.averageHttpCallTime().toFixed(2)}/>
```

**Comment by MykolaGolubyev** [comment]
Well, looks like it is an artifact of an old refactoring. Component later decided to split to seconds and fractions. And doesn't handle fixed inside.

**Comment by MykolaGolubyev** [comment]
Looked at the code again and now I am super confused how that even possible. Code uses `%`.

**Comment by tsiq-karold** [comment]
This particular report does say webtau 1.9 so I'm not looking at old stuff.
