### ISSUE TITLE
Consider narrower classes for static matcher methods

### ISSUE THREAD

**Issue by mattmetlis** [twosigma/webtau#424]
Consider adding a `Matchers` or `ValueMatchers` class with static helper methods for creating `ValueMatcher` instances. There is currently the `Ddjt` class, but that name is hard to remember or discover, and it contains not only helper methods for creating matchers but also other kinds of methods. For example, it contains a method `aMapOf`, which could be confused for a matcher helper method. Also since the `CodeMatcher` instances work differently than `ValueMatcher`s, perhaps they should be in a `CodeMatchers` class rather than being a part of the same class of helper methods as the `ValueMatcher` helper methods.

**Comment by mattmetlis** [comment]
Further, in the new matcher class(es), I would consider not including the 'be' aliases for the methods currently in the `Ddjt` class. For example, `greaterThan` and `beGreaterThan` - only provide `greaterThan`. Since `DataNode` contains the `shouldBe` alias for `should` and `shouldNotBe` alias for `shouldNot`, it seems that users will still be able to write their assertions in ways that will sound correct when spoken. I think having fewer options will make it easier for users to find the matchers they are looking for more quickly.

**Comment by MykolaGolubyev** [comment]
Webtau allows to write mixed tests, i.e. `cli` test that plays nicely with `browser` and `http`. In this case it would not be as convenient to have them separated. Right now, assuming a single static star DSL import, one can simply start writing `http.put` and `cli.run` without fiddling with imports. 

Discovery is a tricky business. If you split into separate classes then you will have to somehow discover those.

**Comment by MykolaGolubyev** [comment]
https://github.com/twosigma/webtau/pull/449
