### ISSUE TITLE
enable sequential runs with different config files

### ISSUE THREAD

**Issue by tsiq-clemens** [twosigma/webtau#426]
use case: I have a set of groovy tests to run against v1 of a swagger API with a docPath of test-artifacts/v1, and a different set of tests to run against v2 of the API, with docPath test-artifacts/v2.
I need to run those tests against different webtau config files.
If I run the 2 suites with the webtau-maven-plugin (using the iterator-maven plugin as wrapper), the 2nd run acknowledges the different config file and test files on the console, but does not apply any of its values for docPath, url, apiSpec, etc.

**Comment by MykolaGolubyev** [comment]
@tsiq-clemens if v1. and v2 need, is there a reason there are two different api files? If users need to be able to see both versions. Or is it for simplified code generation purposes?
I wonder if we need to support multiple spec files to make this more straightforward processes. 

@mattmetlis did you explore further `META-INF/services` approach? Any explicit calls to handlers is meant for webtau extensions and not so much for user code.

**Comment by MykolaGolubyev** [comment]
@tsiq-clemens the easiest would be to figure how to run the maven plugin in a forked mode. Webtau was not designed with multiple runs within the same JVM.

**Comment by tsiq-clemens** [comment]
You're probably right about this, I'll look into that.

**Comment by tsiq-clemens** [comment]
Turns out this forked mode is not trivial. Surefire and similar plugins have a whole set of ProcessXYZ classes to orchestrate forked processes, not unlike the Cli utilities.
Any other ideas how maven can be configured to run the same plugin in different JVMs? I tried different executionIDs, and different phases, but it's still the same JVM.

**Comment by MykolaGolubyev** [comment]
@tsiq-clemens could you please remind me why do you need `iterator-maven plugin` to run something sequential?
