### ISSUE TITLE
extend Swagger coverage recording to response coverage 

### ISSUE THREAD

**Issue by tsiq-clemens** [twosigma/webtau#427]
Currently, webtau records coverage up to the operations level (method + path).

Many swagger specs contain response definitions for happy and error scenarios. It'd be great to report against coverage of each defined response (200, 400, 404, 500, ...).
I'd imagine this to be a separate coverage number from today's operations coverage, similar to method vs class coverage in unit tests.

**Comment by MykolaGolubyev** [comment]
Absolutely! This is a long standing feature. I think at this point we collect all the data we need to be able to swing this. 

It will require some agreement on how we calculate this. I am happy to participate in this discussion.
How about @tsiq-clemens and @tsiq-karold achieve some agreement on this for your needs and then discuss this with @mattmetlis?

**Comment by tsiq-charliem** [comment]
Just spoke with @tsiq-walkert, @tsiq-clemens, and @tsiq-karold about this issue. What makes sense to us is recording whether every (method, path, response) tuple was covered in the test. At first, we could just consume this information in the JSON coverage report. For swagger response codes of "default", we would count that (method, path, response) as being covered if the test contained an assertion on a response code that was different than any response code explicitly contained in the swagger definition for that method and path. Ideally the coverage report would also contain a percentage coverage by method as well as an overall coverage percentage for the whole swagger definition.

**Comment by MykolaGolubyev** [comment]
Do we have any volunteers? Implementation won’t be trivial but also quite possible.

**Comment by tsiq-karold** [comment]
If it's not terribly urgent then I can give this a go over the next few weeks but if it's needed more urgently than that someone else will need to take it.
