### ISSUE TITLE
Replace org.everit.json.schema as dependency 

### ISSUE THREAD

**Issue by MykolaGolubyev** [twosigma/webtau#438]
`everit` uses `org.json:json` that is not Apache License compatible. 
We use `everit` in `webtau-json-schema` module.

**Comment by MykolaGolubyev** [comment]
@tsiq-karold I don't know what are the good alternatives. When you were adding Json Validation, did you stumble across some open source friendly alternatives?

**Comment by tsiq-karold** [comment]
Hmm, it was a while ago... but I think I struggled to find many alternatives.  Ill have another look though.

**Comment by tsiq-karold** [comment]
https://openapi.tools/ lists a few things that I'm going to try sometime this week.
