### ISSUE TITLE
Build javadoc in Travis

### ISSUE THREAD

**Issue by tsiq-karold** [twosigma/webtau#453]
If javadocs are needed for releases, they should be built in Travis.  See #452 .

**Comment by tsiq-karold** [comment]
I think https://github.com/twosigma/webtau/blob/master/pom.xml#L604 is not correct.  I think `java.home` will point to a jre usually which won't have `javadoc`.

**Comment by MykolaGolubyev** [comment]
Wait, how did it work before?

**Comment by tsiq-karold** [comment]
This line:
```xml
                        <javadocExecutable>${java.home}/bin/javadoc</javadocExecutable>
```

Is new since the last release.  1.13 did not have this: https://github.com/twosigma/webtau/blob/1.13/pom.xml

The PR that added it is https://github.com/twosigma/webtau/pull/430 but I'm not sure that specific bit of configuration is needed.  Docs say it's optional so I would suggest we remove it and let Maven figure out where to get javadoc from: https://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html#javadocExecutable

**Comment by MykolaGolubyev** [comment]
Removed the `javadocExecutable`, waiting on travis
