### ISSUE TITLE
support HTTP PATCH method

### ISSUE THREAD

**Issue by tsiq-clemens** [twosigma/webtau#466]
Our API would like to introduce PATCH methods and needs to test them using webtau.
We probably don't need the whole gamut of options like for put or post, but we definitely need to define query parameters and headers.

**Comment by MykolaGolubyev** [comment]
I knew this day would come! :)
Do you have time to implement this?

**Comment by tsiq-clemens** [comment]
I'll give it a shot. Can we cut a release once this is merged?

**Comment by MykolaGolubyev** [comment]
100%

**Comment by tsiq-karold** [comment]
I think we should support all the overrides from the start. It’s a bit tedious but should be mostly copy paste rename.
