### ISSUE TITLE
v1.10 CustomReport is broken by later versions

### ISSUE THREAD

**Issue by tsiq-clemens** [twosigma/webtau#468]
We have a `CustomReport` that wraps a v1.10 `Report`.

It adds 2 data points to the report's `data`:
```        
data.env = cfg.env
data.baseUrl = cfg.baseUrl
```
It further records details about failed scenarios into this `data` about a test's scenario name, file path, and exception message.

Additionally, it outputs a separate json report like so:
```
    private void createFile() {
        def reportPath = cfg.workingDir.resolve('webtau.report.json').toAbsolutePath()
        reportPath.toFile().text = JsonUtils.serializePrettyPrint(data)

        ConsoleOutputs.out('additional report is generated: ', Color.PURPLE, reportPath)
    }
```

How should this report be generated with the current version of webtau?

**Comment by MykolaGolubyev** [comment]
Can you elaborate on wraps `Report`?
Are you implementing `webtau-report/src/main/java/com/twosigma/webtau/report/ReportGenerator.java` And registering it via META-INF or groovy config file?

**Comment by tsiq-clemens** [comment]
```    
private CustomReport(Report report) {
        this.report = report
        this.testEntries = report.testEntries
        this.data = report.createSummary().toMap()
    }
```

The CustomReport does not implement ReportGenerator.

in our webtau.cfg we register `reportGenerator = CustomReport.&generate` , where the generate function takes the Report, creates and initializes a CustomReport and creates the additional json report via `createFile()`

**Comment by tsiq-clemens** [comment]
I was able to update our CustomReport to replicate what it used to do, but had to duplicate some lines from the HtmlReportGenerator:
* reportSummaryToMap()
* parts from generateHtml that create the reportAsMap map

One might argue those functions are not Html specific and could be exposed somewhere meaningful. Thoughts?

**Comment by MykolaGolubyev** [comment]
Ah sorry, I thought I have replied some time back :(
That's probably OK to duplicate map creation as long as you don't duplicate any calculation logic. 

Wanted to make sure you also switched to `WebTauReport` as a parameter to generator.

**Comment by MykolaGolubyev** [comment]
@tsiq-clemens were you able to figure things out?

**Comment by tsiq-clemens** [comment]
yes, I'm all set with this. No calc logic duplicated.
