### ISSUE TITLE
Coverage report inconsistencies

### ISSUE THREAD

**Issue by tsiq-walkert** [twosigma/webtau#493]
Hi. We've noticed that the 'HTTP Coverage' data varies significantly between test runs (please see the attached screenshots). There also appears to be a counting issue with tests run - you can see that between Jan 15 and 16 (roughly 8hrs apart) that they both show 100% run ratio but 208 and 82 total tests respectively. I'm afraid I can't share the full reports but please let me know what I might be able to do to help debug.
Thanks

### Jan 9
![Report Jan 9](https://user-images.githubusercontent.com/49456737/72539159-e3476b80-384c-11ea-8f1a-f837211a04b3.png)

### Jan 15
<img width="540" alt="Report Jan 15" src="https://user-images.githubusercontent.com/49456737/72539162-e5a9c580-384c-11ea-8db6-40f683b4d71b.png">

### Jan 16
<img width="545" alt="Report Jan 16" src="https://user-images.githubusercontent.com/49456737/72539167-e6daf280-384c-11ea-9ae3-8899cf7fe20c.png">

**Comment by MykolaGolubyev** [comment]
Do you have any insights into why you have a different `Tests total`? Or are you saying that the report incorrectly shows 82?

**Comment by tsiq-walkert** [comment]
<sigh> - this may all be to do with the way in which we're invoking >1 webtau for certain subsets of tests. I'll need to clarify and then update. Apologies for the potential false alarm.

**Comment by MykolaGolubyev** [comment]
@tsiq-walkert should we close this?

**Comment by tsiq-walkert** [comment]
Sure - thanks @MykolaGolubyev. I'll open a fresh ticket if I get some concrete data.
