### ISSUE TITLE
Default env logging is confusing

### ISSUE THREAD

**Issue by tsiq-karold** [twosigma/webtau#5]
```
localHost:tests karol$ ~/Dev/webtau/dist/webtau scenarios/*
       env: local                                   // from command line argument
```
Clearly, the comment is not correct as no env was specified on command line!

**Comment by MykolaGolubyev** [comment]
closing manually as it was fixed with PR. I think "fixes #x" should be part of a commit and not PR comment for it to auto close

**Comment by MykolaGolubyev** [comment]
misplaced PRs, re-open, the PR that closes this has conflicts.
