### ISSUE TITLE
metadata property access simplification

### ISSUE THREAD

**Issue by tsiq-clemens** [twosigma/webtau#500]
To get the custom "owner" value of a test's metadata, you have to write `test.getMetadata().toMap().get("owner")`

Ideally, custom reports could just use `test.metadata.owner`

Previous attempts:

`test.metadata["owner"]` => `groovy.lang.MissingPropertyException: No such property: owner for class: com.twosigma.webtau.reporter.WebTauTestMetadata`

and

`entry.metadata.get("owner")` => 
```
No signature of method: com.twosigma.webtau.reporter.WebTauTestMetadata.get() is applicable for argument types: (String) values: [owner]
Possible solutions: getAt(java.lang.String), grep(), grep(java.lang.Object), wait(), any(), wait(long)
```

**Comment by MykolaGolubyev** [comment]
Are you on the latest? I see `get` is defined:
```
public <E> E get(String key) {
    return (E) metadata.get(key);
}
```

**Comment by MykolaGolubyev** [comment]
I think method we added right after the release. Added test to confirm that access works as expected

**Comment by tsiq-clemens** [comment]
confirmed locally against 1.19-SNAPSHOT
