### ISSUE TITLE
Show failed tests at the top

### ISSUE THREAD

**Issue by tsiq-chandru** [twosigma/webtau#75]
Currently, we order the tests alphabetically in the HTML report. Would be nice to see the failed errors at the top (ideally with a copyable details).

**Comment by MykolaGolubyev** [comment]
do you mean inside the html report? I think it is very reasonable.
What details do you want to be copied? Last assertion message?

**Comment by tsiq-chandru** [comment]
Yup - updated the original comment. And yes, the assertion message + some details that would help someone trying to quickly troubleshoot

**Comment by MykolaGolubyev** [comment]
Not sure I follow the details part. Workflow I had in mine was around sharing failures was to share a link. As you navigate around issues and tabs link is updated to point to that place.

All that information is useful to investigate, but copying it in a clipboard may not make sense. 
I would rather copy report url (will only work when we have Jenkins that hosts them, or S3).

**Comment by tsiq-chandru** [comment]
A sharable link works!

**Comment by MykolaGolubyev** [comment]
should be closed by #77
